/* Automatically generated by './build/bin/build-entry.js' */

import FileUpload from '../packages/file-upload/index';
import Icon from '../packages/icon/index';
import Dialog from '../packages/dialog/index';
import Editor from '../packages/Tinymce/index';
import Pagination from '../packages/pagination/index';
import Table from '../packages/table/index';
import TableTree from '../packages/table-tree/index';
import RegionPicker from '../packages/region-picker/index';

import Http from './axios/index';
import * as Tools from './utils/global.common';
import emitter from './mixins/emitter';
import boxer from './directive/boxer';
// import dragDialog from './directive/dragDialog';
//import DatePicker from '../packages/date-picker/index';
//import ImportExcel from '../packages/import-excel/index';
//import Button from '../packages/button/index';
//import Print from '../packages/print/index';
const components = [
    //DatePicker,
    //ImportExcel,
    //Button,
    //Print,
    Icon,
    FileUpload,
    Dialog,
    Editor,
    Pagination,
    Table,
    TableTree,
    RegionPicker
];

const install = function (Vue, opts = {}) {
    components.forEach(component => {
        Vue.component(component.name, component);
    });
    Vue.prototype.Http = Http;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}
export {
    emitter,
    Tools,
    boxer,
    Http
};
export default {
    install
};